### ISSUE TITLE
Replace `assert` statements in Marshall.hpp with run-time error handling

### ISSUE THREAD

**Issue by richey-v** [cross-language-cpp/djinni-support-lib#16]
The `assert` statements were discovered due to a warning, reported in #13.  The warnings were addressed in #15.

The apparent purpose of the `assert`s is to ensure that a `NewByteArray` can be created that is large enough to handle the data to be marshaled.  There is no run-time error handling other than the `assert` statement, so if those are optimized away, there is no safety at all.

**Comment by a4z** [comment]
I agree that there is no safety , except a check in a debug build (with an assert failure).

But I have difficult to see what else to do.  
Exceptions, just crash ....  ? This might result in the same , because, how could you handle such an exception. 
And then there is of course the question of the likeliness of such an event, and if we are willy to pay the price of additional code in the release build for this scenario? 

It would be good to find answers to those questions to come up with a strategy for a better solution, if there is any

**Comment by a4z** [comment]
After skimming again though our assert usages, I am closing that issue.

Asserts have a defined use case in C++, that is, check a condition in debug build and don't check (remove that code) in release builds.
There are many asserts, and they are used in the spirit of that use case.

If there is any special assert that should be implemented as a runtime exception also in release builds, there should be specific ticket for it, so it can be discussed. And if there is an exception implementation, tests need be added to trigger that problem and verify exceptions are thrown accordingly.

A general ticket like this, that wants to remove all asserts, can not be implemented, since asserts have a real use case.
