### ISSUE TITLE
Java/JNI thread problems

### ISSUE THREAD

**Issue by paulo-coutinho** [cross-language-cpp/djinni-support-lib#48]
Hi,

I have a strange problem when i call one java method to make a log:

![image](https://user-images.githubusercontent.com/395096/128593993-f1c6d797-108c-4f94-ac7f-8a74b14cbe80.png)

First step:

![image](https://user-images.githubusercontent.com/395096/128594002-bff0c1e7-c6e2-4112-840d-ce89a3186569.png)

Second step:

![image](https://user-images.githubusercontent.com/395096/128594008-378c187a-14e9-4584-bc0d-f62277275c01.png)

Third step:

![image](https://user-images.githubusercontent.com/395096/128594027-b1625d0d-bfc3-4e07-9780-3d9258f4b040.png)

Forty step:

![image](https://user-images.githubusercontent.com/395096/128594034-af949970-613b-4602-a115-413f3e28310c.png)

Obs:

This is very strange, because other call to the same method don't have error, only this in full application.

You can see that first is called ([SimpleHttpServerRequestHandlerFactory : constructor]) and others too before:

![image](https://user-images.githubusercontent.com/395096/128594080-cf01543c-e844-444e-a00a-0f20f67cae3d.png)

**Comment by paulo-coutinho** [comment]
Hum...i think that poco http server is calling it on other thread!

There is a way to fix this?

**Comment by a4z** [comment]
Did you compile the support lib with thread support? 
(Calling cmake with `-DJNI_CPP_THREAD_ATTACH=ON`)

**Comment by paulo-coutinho** [comment]
Hi,

In my case it is embedded into my project.

https://github.com/ezored/ezored/tree/master/files/modules/support-lib

And i add files manually:

```
file(GLOB H_FILES_CXX "${PROJECT_MODULES_PATH}/support-lib/djinni/jni/main-ext/*.hpp")
file(GLOB S_FILES_CXX "${PROJECT_MODULES_PATH}/support-lib/djinni/jni/main-ext/*.cpp")

file(GLOB H_FILES_SUPPORT "${PROJECT_MODULES_PATH}/support-lib/djinni/*.hpp")
file(GLOB S_FILES_SUPPORT "${PROJECT_MODULES_PATH}/support-lib/djinni/*.cpp")

file(GLOB H_FILES_SUPPORT_PLATFORM "${PROJECT_MODULES_PATH}/support-lib/djinni/jni/*.hpp")
file(GLOB S_FILES_SUPPORT_PLATFORM "${PROJECT_MODULES_PATH}/support-lib/djinni/jni/*.cpp")
```

There is any way to do it only to this files?

**Comment by paulo-coutinho** [comment]
Hi,

Nice, it work.

It still experimental? There is any problem with this?

**Comment by a4z** [comment]
> There is any way to do it only to this files?

Yes there is, see `target_compile_definitions(djinni_support_lib PRIVATE EXPERIMENTAL_AUTO_CPP_THREAD_ATTACH)` 
So you need to compile your djinni code with `EXPERIMENTAL_AUTO_CPP_THREAD_ATTACH` defined.

> It still experimental? 

kind of not, some people doing this since dropbox time, so we decided to make it public accessible.

> There is any problem with this?

I do not know about any, except, it is better to have an app architecture that does not require that since things can get wild with cross lang threading involved.

**Comment by paulo-coutinho** [comment]
I have an app that im testing it, android, ios and desktop.

https://github.com/ezored/ezored

But his branch with http server:
https://github.com/ezored/ezored/tree/version-3

I have added the flag and need wait CI finish:
https://github.com/ezored/ezored/actions

But i tested locally making a stress-test to http server and it work fine after that flag, but i don't know how to test all things that you need.

You can use my android app to test, only need open it and call their IP + ":9090" on browser.

On each request a new thread is created and inside it have Logger.d, Logger.e, etc that is a djinni use with problem without that flag, and what i posted on issue.

When i compile with the flag the problem disappear.

**Comment by a4z** [comment]
Glad to hear the threading feature works also for you. 

I think we will remove the `EXPERIMENTAL` part from `EXPERIMENTAL_AUTO_CPP_THREAD_ATTACH` in some near future since this is imho used enough to do so. Just forgot about it since we wrap it via cmake. 

If everything works for you now, and there are no further question on the topic, please feel free to close the issue.
Thanks for your feedback @paulo-coutinho !
