### ISSUE TITLE
Problems when use new support library for iOS

### ISSUE THREAD

**Issue by paulo-coutinho** [cross-language-cpp/djinni-support-lib#61]
Hi,

Im taking error:

```
/Users/runner/work/ezored/ezored/files/modules/support-lib/djinni/objc/DJIError.h:23:55: error: unknown type name 'NSString'
[[noreturn]] void throwUnimplemented(const char *ctx, NSString *msg);
                                                      ^
1 error generated.
```

Full log:
https://github.com/ezored/ezored/runs/3747388613?check_suite_focus=true#step:13:403

Can anyone help me with this?

**Comment by paulo-coutinho** [comment]
I found the problem, you need include foundation header. Like mine:

https://github.com/ezored/ezored/blob/master/files/modules/support-lib/djinni/objc/DJIError.h#L19

**Comment by a4z** [comment]
hm, we have the include here , https://github.com/cross-language-cpp/djinni-support-lib/blob/0a201f206dc15c59ab54a917718d4991dbc1bb90/djinni/objc/DJIError.mm#L17
above the include of DJIError.h

so that is fine, otherwise our CI could not build the DJIError.mm file, as your CI fails to do. 

so I wonder if you mix our  headers with some old sources that miss that include, which are definitely not our sources...... ? 

Please double check and report back.

**Comment by paulo-coutinho** [comment]
Hi,

I copy and paste support lib only.

Your code is:
```
#include "DJIError.h"
#include <Foundation/Foundation.h>
```

Your foundation header is after `DJIError.h`, where is the problem.

You need add to the header, since NSString is used there first.

**Comment by a4z** [comment]
Have you checked the file I linked to? 

I do not know how it happend that you have a different version, but the code in this repos has
```
#include <Foundation/Foundation.h>
#include "DJIError.h"
#include <exception>
....
```

as you can easily see here: 
https://github.com/cross-language-cpp/djinni-support-lib/blob/0a201f206dc15c59ab54a917718d4991dbc1bb90/djinni/objc/DJIError.mm#L17


So whatever you refer to, it does not seem to me it is a problem in the code we have in this repo.
The code in your repos is different that what we have in here.

**Comment by paulo-coutinho** [comment]
Sorry, i don't know what i open that i see other thing. Forgive me please.

**Comment by a4z** [comment]
No worries Paulo, you work a lot and such days exist, I know that from my self.

**Comment by paulo-coutinho** [comment]
I found the problem.

Clang-Format is changing import order.

It is changing to:
```
#include "DJIError.h"
#include <Foundation/Foundation.h>
```

Because first import, for convenience, is the header related to current implementation.

There is any chance to make it available inside `DJIError.h`?

This is a good practice, like this docs from Google:
https://google.github.io/styleguide/objcguide.html

**Comment by a4z** [comment]
Wow Paulo, what a valuable finding ! Thank you so much!! 

This is kind of a problem we need to think about , 
there might be an option to control that to not re-order imports but  ... oh no ...  I do not like that we need to care about a formatting tool, even if I like clang format a lot

I reopen the issue so we do not forget about that, but I think we will start a new issue for that topic, since we now can explicit name it
