### ISSUE TITLE
I use djinni about 6 years , but still not support inherit

### ISSUE THREAD

**Issue by kinglezhuang** [cross-language-cpp/djinni-support-lib#68]
For my understand, we can support inherit in future, also need follow OOO design.
std can support is_base_of / etc... meta programing, so we can use that to support inherit.
also we can forbidden c++ diamond inheritance

**Comment by a4z** [comment]
I am not sure I understand this correct
> For my understand, we can support inherit in future, also need follow OOO design.
There are not a lot of things to inherit from in the support lib, but the whole implementation of djinni generated interface code is base on inheritance.

Can you please explain what you mean ? 

_Just 2 notes:_
`std::is_base_of` is in the C++ standard since c++11
see  https://en.cppreference.com/w/cpp/types/is_base_of  

C++ diamond inheritance is not an issue, it was always just a marketing FUD gag from Sun people to push Java.
It's always up to user to make what ever they want, if they want diamond inheritance, fine, then they hopefully know about virtual inheritance. An awesome intro and technical explanation to virtual inheritance can be found here: https://mariusbancila.ro/blog/2021/11/16/virtual-inheritance-in-c/

**Comment by kinglezhuang** [comment]
@a4z 

Thank you for your reply.
If someone uses IDL for interfaces definition. Now all interfaces are flat, non-inherited relationship.
Eg: 
parent = interface +j +o
{}

child : parent = interface +j +o
{}

In our practice, without inheritance, we need a lot of extra work to use these interfaces that are actually inherited.
I was going to refactor djinni next year, but I found that the community is maintained now, and I very much hope that the community will support this feature as well.

**Comment by jothepro** [comment]
Not sure if it helps but there is a fork that supports inheritance for records: [hiennguyenle/finn#extend-record](https://github.com/hiennguyenle/finn#extend-record).

If you are planning to implement interface inheritance, we are looking forward to your PR! 😊

**Comment by a4z** [comment]
Closed due to inactivity, please feel free to re-open this PR in case the topic is still actual.
